# Generated by Django 4.1.3 on 2023-03-12 08:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farmer", "0002_farmer_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("storage_capacity", models.PositiveIntegerField()),
                (
                    "phone_number",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_phone_number",
                                message="Phone number must be valid",
                                regex="^\\d{10,11}$",
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("reservation_date", models.DateField()),
                (
                    "crop_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farmer.crop"
                    ),
                ),
                (
                    "famer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farmer.farmer"
                    ),
                ),
                (
                    "warehouse_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_phone_number",
                                message="Phone number must be valid",
                                regex="^\\d{10,11}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=12, null=True)),
                (
                    "warehouse_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Crop_stored",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("storage_date", models.DateField()),
                ("quantity", models.PositiveIntegerField()),
                (
                    "crop_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farmer.crop"
                    ),
                ),
                (
                    "famer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farmer.farmer"
                    ),
                ),
                (
                    "warehouse_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.warehouse",
                    ),
                ),
            ],
        ),
    ]
