# Generated by Django 4.0.1 on 2023-04-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_farmer_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crop',
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
    ]
